#!/bin/bash
# NEXTFLOW TASK: metaspades (KK01_B_1a_err_correct)
set -e
set -u
NXF_DEBUG=${NXF_DEBUG:=0}; [[ $NXF_DEBUG > 1 ]] && set -x
NXF_ENTRY=${1:-nxf_main}


nxf_date() {
    local ts=$(date +%s%3N); [[ $ts == *3N ]] && date +%s000 || echo $ts
}

nxf_env() {
    echo '============= task environment ============='
    env | sort | sed "s/\(.*\)AWS\(.*\)=\(.\{6\}\).*/\1AWS\2=\3xxxxxxxxxxxxx/"
    echo '============= task output =================='
}

nxf_kill() {
    declare -a children
    while read P PP;do
        children[$PP]+=" $P"
    done < <(ps -e -o pid= -o ppid=)

    kill_all() {
        [[ $1 != $$ ]] && kill $1 2>/dev/null || true
        for i in ${children[$1]:=}; do kill_all $i; done
    }

    kill_all $1
}

nxf_mktemp() {
    local base=${1:-/tmp}
    if [[ $(uname) = Darwin ]]; then mktemp -d $base/nxf.XXXXXXXXXX
    else TMPDIR="$base" mktemp -d -t nxf.XXXXXXXXXX
    fi
}

on_exit() {
    exit_status=${nxf_main_ret:=$?}
    printf $exit_status > /gpfs1/data/idiv_kuesel/WOverholt/Siberia/nextflow_metagenomic_binning/work/38/8dadf3464eef2a72c7adacd977153d/.exitcode
    set +u
    [[ "$tee1" ]] && kill $tee1 2>/dev/null
    [[ "$tee2" ]] && kill $tee2 2>/dev/null
    [[ "$ctmp" ]] && rm -rf $ctmp || true
    exit $exit_status
}

on_term() {
    set +e
    [[ "$pid" ]] && nxf_kill $pid
}

nxf_launch() {
    /bin/bash -ue /gpfs1/data/idiv_kuesel/WOverholt/Siberia/nextflow_metagenomic_binning/work/38/8dadf3464eef2a72c7adacd977153d/.command.sh
}

nxf_stage() {
    true
    # stage input files
    rm -f KK01_B_1a_err_correct_R1.fastq
    rm -f KK01_B_1a_err_correct_R2.fastq
    ln -s /gpfs1/data/idiv_kuesel/WOverholt/Siberia/02_qaqc/deplete_euks/error_correct/KK01_B_1a_err_correct_R1.fastq KK01_B_1a_err_correct_R1.fastq
    ln -s /gpfs1/data/idiv_kuesel/WOverholt/Siberia/02_qaqc/deplete_euks/error_correct/KK01_B_1a_err_correct_R2.fastq KK01_B_1a_err_correct_R2.fastq
}

nxf_unstage() {
    true
    [[ ${nxf_main_ret:=0} != 0 ]] && return
}

nxf_main() {
    trap on_exit EXIT
    trap on_term TERM INT USR1 USR2

    NXF_SCRATCH=''
    [[ $NXF_DEBUG > 0 ]] && nxf_env
    touch /gpfs1/data/idiv_kuesel/WOverholt/Siberia/nextflow_metagenomic_binning/work/38/8dadf3464eef2a72c7adacd977153d/.command.begin
    set +u
    # conda environment
    source activate /home/overholt/.conda/envs/metagenomics
    set -u
    [[ $NXF_SCRATCH ]] && echo "nxf-scratch-dir $HOSTNAME:$NXF_SCRATCH" && cd $NXF_SCRATCH
    nxf_stage

    set +e
    local ctmp=$(set +u; nxf_mktemp /dev/shm 2>/dev/null || nxf_mktemp $TMPDIR)
    local cout=$ctmp/.command.out; mkfifo $cout
    local cerr=$ctmp/.command.err; mkfifo $cerr
    tee .command.out < $cout &
    tee1=$!
    tee .command.err < $cerr >&2 &
    tee2=$!
    ( nxf_launch ) >$cout 2>$cerr &
    pid=$!
    wait $pid || nxf_main_ret=$?
    wait $tee1 $tee2
    nxf_unstage
}

$NXF_ENTRY
